CREATE TABLE rotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL CHECK (btrim(nome) <> ''),
    turno VARCHAR(30) NOT NULL CHECK (btrim(turno) <> ''),
    origem VARCHAR(150) NOT NULL CHECK (btrim(origem) <> ''),
    destino VARCHAR(150) NOT NULL CHECK (btrim(destino) <> '')
);
CREATE UNIQUE INDEX uk_rotas_nome ON rotas (lower(nome));

CREATE TABLE alunos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL CHECK (btrim(nome) <> ''),
    matricula VARCHAR(40) NOT NULL CHECK (btrim(matricula) <> ''),
    turma VARCHAR(60) NOT NULL CHECK (btrim(turma) <> ''),
    responsavel VARCHAR(150) NOT NULL CHECK (btrim(responsavel) <> ''),
    rota_id BIGINT NOT NULL REFERENCES rotas(id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX uk_alunos_matricula ON alunos (lower(matricula));
CREATE INDEX ix_alunos_rota ON alunos (rota_id);
