CREATE TABLE motoristas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL CHECK (btrim(nome) <> ''),
    cnh VARCHAR(11) NOT NULL UNIQUE CHECK (cnh ~ '^[0-9]{11}$'),
    telefone VARCHAR(30) NOT NULL CHECK (btrim(telefone) <> ''),
    usuario_id BIGINT NOT NULL UNIQUE REFERENCES usuarios(id) ON DELETE RESTRICT
);
CREATE TABLE veiculos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa VARCHAR(8) NOT NULL UNIQUE,
    modelo VARCHAR(100) NOT NULL CHECK (btrim(modelo) <> ''),
    capacidade INTEGER NOT NULL CHECK (capacidade BETWEEN 1 AND 200),
    motorista_id BIGINT REFERENCES motoristas(id) ON DELETE RESTRICT
);
CREATE INDEX ix_veiculos_motorista ON veiculos(motorista_id);
ALTER TABLE rotas ADD COLUMN veiculo_id BIGINT REFERENCES veiculos(id) ON DELETE RESTRICT;
CREATE INDEX ix_rotas_veiculo ON rotas(veiculo_id);
