ALTER TABLE alunos ADD COLUMN responsavel_usuario_id BIGINT REFERENCES usuarios(id) ON DELETE RESTRICT;
ALTER TABLE alunos ADD COLUMN parada_ida_id BIGINT REFERENCES paradas(id) ON DELETE RESTRICT;
ALTER TABLE alunos ADD COLUMN parada_volta_id BIGINT REFERENCES paradas(id) ON DELETE RESTRICT;
CREATE INDEX ix_alunos_responsavel ON alunos(responsavel_usuario_id);

CREATE TABLE agendamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id BIGINT NOT NULL REFERENCES alunos(id) ON DELETE RESTRICT,
    data_servico DATE NOT NULL,
    trajeto VARCHAR(5) NOT NULL CHECK (trajeto IN ('IDA','VOLTA')),
    status VARCHAR(12) NOT NULL CHECK (status IN ('CONFIRMADO','CANCELADO')),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(aluno_id,data_servico,trajeto)
);
CREATE TABLE viagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rota_id BIGINT NOT NULL REFERENCES rotas(id) ON DELETE RESTRICT,
    motorista_usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    rota_nome VARCHAR(150) NOT NULL,
    motorista_nome VARCHAR(150) NOT NULL,
    placa VARCHAR(8) NOT NULL,
    data_servico DATE NOT NULL,
    trajeto VARCHAR(5) NOT NULL CHECK (trajeto IN ('IDA','VOLTA')),
    status VARCHAR(20) NOT NULL DEFAULT 'EM_ANDAMENTO' CHECK (status IN ('EM_ANDAMENTO','ENCERRADA')),
    ponto_atual INTEGER NOT NULL DEFAULT 1,
    no_ponto BOOLEAN NOT NULL DEFAULT false,
    versao BIGINT NOT NULL DEFAULT 0,
    iniciada_em TIMESTAMPTZ NOT NULL,
    encerrada_em TIMESTAMPTZ,
    UNIQUE(rota_id,data_servico,trajeto)
);
CREATE INDEX ix_viagens_motorista ON viagens(motorista_usuario_id,data_servico);
CREATE TABLE viagem_paradas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viagem_id BIGINT NOT NULL REFERENCES viagens(id) ON DELETE RESTRICT,
    parada_original_id BIGINT NOT NULL,
    ordem INTEGER NOT NULL,
    local VARCHAR(150) NOT NULL,
    referencia VARCHAR(250) NOT NULL,
    horario TIME NOT NULL,
    tipo VARCHAR(12) NOT NULL,
    UNIQUE(viagem_id,ordem)
);
CREATE TABLE participantes (
    viagem_id BIGINT NOT NULL REFERENCES viagens(id) ON DELETE RESTRICT,
    aluno_id BIGINT NOT NULL REFERENCES alunos(id) ON DELETE RESTRICT,
    aluno_nome VARCHAR(150) NOT NULL,
    embarque_ordem INTEGER NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'PENDENTE' CHECK (status IN ('PENDENTE','PRESENTE','AUSENTE')),
    entrada_em TIMESTAMPTZ,
    saida_em TIMESTAMPTZ,
    registrado_em TIMESTAMPTZ,
    PRIMARY KEY(viagem_id,aluno_id)
);
CREATE TABLE eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    viagem_id BIGINT REFERENCES viagens(id) ON DELETE RESTRICT,
    entidade VARCHAR(30) NOT NULL,
    registro_id BIGINT NOT NULL,
    acao VARCHAR(40) NOT NULL,
    detalhe TEXT NOT NULL,
    em TIMESTAMPTZ NOT NULL
);
CREATE INDEX ix_eventos_viagem ON eventos(viagem_id,em);
