ALTER TABLE usuarios ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE alunos ADD COLUMN usuario_id BIGINT UNIQUE REFERENCES usuarios(id) ON DELETE RESTRICT;
ALTER TABLE alunos ADD COLUMN curso VARCHAR(150) NOT NULL DEFAULT '';
ALTER TABLE alunos ADD COLUMN periodo VARCHAR(60) NOT NULL DEFAULT '';
ALTER TABLE alunos ADD COLUMN telefone VARCHAR(30) NOT NULL DEFAULT '';
ALTER TABLE motoristas ADD COLUMN cpf VARCHAR(11);
CREATE UNIQUE INDEX uk_motoristas_cpf ON motoristas(cpf) WHERE cpf IS NOT NULL;
ALTER TABLE motoristas ADD COLUMN validade_cnh DATE;
ALTER TABLE veiculos ADD COLUMN ano_fabricacao INTEGER CHECK (ano_fabricacao BETWEEN 1900 AND 2100);
ALTER TABLE veiculos ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE rotas ADD COLUMN descricao VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE rotas ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE paradas ADD COLUMN endereco VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE paradas ADD COLUMN latitude DOUBLE PRECISION CHECK (latitude BETWEEN -90 AND 90);
ALTER TABLE paradas ADD COLUMN longitude DOUBLE PRECISION CHECK (longitude BETWEEN -180 AND 180);
ALTER TABLE paradas ADD CONSTRAINT ck_coordenadas CHECK ((latitude IS NULL) = (longitude IS NULL));
ALTER TABLE viagem_paradas ADD COLUMN endereco VARCHAR(250) NOT NULL DEFAULT '';
ALTER TABLE viagem_paradas ADD COLUMN latitude DOUBLE PRECISION;
ALTER TABLE viagem_paradas ADD COLUMN longitude DOUBLE PRECISION;
CREATE TABLE responsaveis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE REFERENCES usuarios(id) ON DELETE RESTRICT,
    cpf VARCHAR(11) UNIQUE,
    telefone VARCHAR(30) NOT NULL DEFAULT ''
);
CREATE TABLE responsaveis_alunos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    responsavel_id BIGINT NOT NULL REFERENCES responsaveis(id) ON DELETE RESTRICT,
    aluno_id BIGINT NOT NULL REFERENCES alunos(id) ON DELETE RESTRICT,
    parentesco VARCHAR(60) NOT NULL DEFAULT '',
    UNIQUE(responsavel_id,aluno_id)
);
INSERT INTO responsaveis(usuario_id) SELECT DISTINCT responsavel_usuario_id FROM alunos WHERE responsavel_usuario_id IS NOT NULL;
INSERT INTO responsaveis_alunos(responsavel_id,aluno_id) SELECT r.id,a.id FROM alunos a JOIN responsaveis r ON r.usuario_id=a.responsavel_usuario_id;
CREATE TABLE alunos_pontos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id BIGINT NOT NULL REFERENCES alunos(id) ON DELETE CASCADE,
    parada_id BIGINT NOT NULL REFERENCES paradas(id) ON DELETE RESTRICT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE(aluno_id,parada_id)
);
INSERT INTO alunos_pontos(aluno_id,parada_id) SELECT id,parada_ida_id FROM alunos WHERE parada_ida_id IS NOT NULL UNION SELECT id,parada_volta_id FROM alunos WHERE parada_volta_id IS NOT NULL;
ALTER TABLE agendamentos ADD COLUMN parada_id BIGINT REFERENCES paradas(id) ON DELETE RESTRICT;
UPDATE agendamentos g SET parada_id=CASE WHEN g.trajeto='IDA' THEN a.parada_ida_id ELSE a.parada_volta_id END FROM alunos a WHERE a.id=g.aluno_id;
CREATE TABLE rotas_veiculos (
    rota_id BIGINT NOT NULL REFERENCES rotas(id) ON DELETE CASCADE,
    veiculo_id BIGINT NOT NULL REFERENCES veiculos(id) ON DELETE RESTRICT,
    PRIMARY KEY(rota_id,veiculo_id)
);
CREATE TABLE rotas_motoristas (
    rota_id BIGINT NOT NULL REFERENCES rotas(id) ON DELETE CASCADE,
    motorista_id BIGINT NOT NULL REFERENCES motoristas(id) ON DELETE RESTRICT,
    PRIMARY KEY(rota_id,motorista_id)
);
ALTER TABLE viagens ADD COLUMN veiculo_id BIGINT REFERENCES veiculos(id) ON DELETE RESTRICT;
UPDATE viagens v SET veiculo_id=c.id FROM veiculos c WHERE c.placa=v.placa;
